BNS-22: User creation
bazarnetwork/bazar-web pull request #1
Opened 2022-09-29 15:24 UTC by ncoello-cft

BNS-32 Initial APP creation

2022-09-29 15:40 UTC, diegocortes-cafeto approved these changes
Looks good for first structure of project: 

> ReactJS (Done)
> TypeScript (Done)

Make sure to use NodeJS with the next versions: 16.15.0 or 16.16.0

2022-09-30 14:01 UTC, diegocortes-cafeto commented on .vscode/extensions.json
> +    "recommendations": [
this file can be ingnored

2022-09-30 14:03 UTC, diegocortes-cafeto requested changes
Please, ignore the .vscode folder.

2022-10-03 15:14 UTC, davidcormor approved these changes

2022-10-03 15:56 UTC, diegocortes-cafeto approved these changes

2022-10-03 15:57 UTC, davidcormor approved these changes

2022-10-03 21:53 UTC, davidcormor approved these changes

2022-10-04 17:20 UTC, diegocortes-cafeto approved these changes

2022-10-04 21:35 UTC, davidcormor approved these changes

2022-10-25 19:48 UTC, merged